---

  - name: Install Nginx
    package:
      name: nginx
      state: present

  - name: Start Nginx
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Create nginx config
    template:
      src: default.j2
      dest: /etc/nginx/sites-available/default
    notify: restart nginx
