---

- name: Install apache2
  package:
    name: apache2
    state: present

- name: Start apache2
  service:
    name: apache2
    state: started
    enabled: yes

- name: Change UID www-data
  user:
    name: www-data
    uid: 1101

- name: Change GID www-data
  group:
    name: www-data
    gid: 1100
