---

- name: Install PHP5.6
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "php{{php_versionv1}}"
    - "php{{php_versionv1}}-fpm"
    - "php{{php_versionv1}}-mysql"
    - "php{{php_versionv1}}-xml"
    - "php{{php_versionv1}}-gd"
    - "php{{php_versionv1}}-mbstring"

- apache2_module:
    state : present
    name: "{{item}}"
  loop:
    - proxy_fcgi
    - setenvif
  notify: Restart apache2

- meta: flush_handlers

- name: Remove version7
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  loop:
    - "php{{php_versionv2}}*"

- name: Enabling conf
  command: a2enconf "php{{php_versionv1}}-fpm.conf"
  notify: Restart apache2
