---

- name: Create directory data wiki
  file:
    path: "{{data_wiki}}"
    state: directory
    mode: '0755'
    recurse: yes

- name: Dump database
  mysql_db:
    state: dump
    name:
      - mediawiki_db
    target: "{{data_wiki}}/backup.sql.gz"

- name: Dump
  command: php "{{mediawiki_apache}}/md3_01.00.00_data/maintenance/dumpBackup.php" --full >  "{{data_wiki}}/wikidoneesv1.xml"

- name: Copy Localsettings.php
  copy:
    src: "{{mediawiki_apache}}/md3_01.00.00_data/LocalSettings.php"
    dest: "{{data_wiki}}"
    remote_src: yes

- name: Archive mediawiki01.00.00
  archive:
    path: "{{mediawiki_apache}}/md3_01.00.00_data"
    dest: "{{data_wiki}}/md3_01.00.00_data"
    format: gz
