---

- name: Install mysql
  package:
    name: "{{item}}"
    state: present
  loop:
    - mysql-server
    - python-mysqldb

- name: Create mysqld.cnf
  copy:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf

- name: Start mysql
  service:
    name: mysql
    state: started

- name: Enable MySQL
  service:
    name: mysql
    enabled: yes

- pause:
    seconds: 15

- name: Remove anonymous users
  mysql_user:
    name: ""
    state: absent

- name: Remove test database
  mysql_db:
    name: test
    state: absent

- name: Update root password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{mysql_new_root_pass.stdout}}"
  loop:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Create my.cnf
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf

- name: Create MySQL database
  mysql_db:
    name: "{{mysql_dbname}}"
    state: present
  notify: stop mysql

- name: Create MySQL user
  mysql_user:
    name: "{{mysql_user}}"
    host: localhost
    password: "{{mysql_passwd}}"
    priv: "{{mysql_dbname}}.*:ALL"
