---

- name: Install mysql
  package:
    name: "{{item}}"
    state: present
  loop:
    - mysql-server
    - python-mysqldb

- name: Create mysqld.cnf
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify: restart mysql

- name: Generate new root password
  command: openssl rand -hex 7
  args:
    creates: /root/.my.cnf
  register: mysql_new_root_pass

- name: Remove anonymous users
  mysql_user:
    name: ""
    state: absent
  when: mysql_new_root_pass.changed

- name: Remove test database
  mysql_db:
    name: test
    state: absent
  when: mysql_new_root_pass.changed

- name: Output new root password
  debug:
    msg: "New root password is {{mysql_new_root_pass.stdout}}"
  when: mysql_new_root_pass.changed

- name: Update root password
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{mysql_new_root_pass.stdout}}"
  loop:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
- name: Create my.cnf
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf

- name: Create MySQL database
  mysql_db:
    name: "{{mysql_dbname}}"
    state: present

- name: Create MySQL user
  mysql_user:
    name: "{{mysql_user}}"
    host: localhost
    password: "{{mysql_passwd}}"
    priv: wordpress.*:ALL
