---

- name: Copy package_2 on LIVR
  copy:
    src: "Package_2/{{item}}"
    dest: "{{mediawiki_LIVR2}}"
  loop:
    - md3_01.01.00_data.tar.gz
    - Theme-REL1_34-b71d3ac.tar.gz
    - LoGo.tar.gz
    - dump_image.tar.gz

- name: Unarchive md3_01.01.00_data
  unarchive:
    src: "{{mediawiki_LIVR2}}/md3_01.01.00_data.tar.gz"
    dest: "{{mediawiki_apache}}"
    mode: 0755
    owner: www-data
    group: www-data
    remote_src: yes

- name: Unarchive md3_01.01.00_data
  unarchive:
    src: "{{mediawiki_LIVR2}}/{{item.source}}"
    dest: "{{mediawiki_apache}}/md3_01.01.00_data/{{item.destination}}"
    mode: 0755
    owner: www-data
    group: www-data
    remote_src: yes
  loop:
    - { source: Theme-REL1_34-b71d3ac.tar.gz, destination: "/extensions/" }
    - { source: LoGo.tar.gz, destination: "/resources/assets/" }

- name: Copy images on LIVR2
  copy:
    src: "{{mediawiki_LIVR1}}"
    dest: "{{mediawiki_LIVR2}}"
    remote_src: yes

- name: Import Localsettings.php
  copy:
    src: LocalSettings.php
    dest: "{{mediawiki_apache}}/md3_01.01.00_data"

- name: Update.php
  command: php "{{mediawiki_apache}}/md3_01.01.00_data/maintenance/update.php"

- name: Import images
  command: php "{{mediawiki_apache}}/md3_01.01.00_data/maintenance/importImages.php" "{{mediawiki_LIVR2}}"

- name: Copy new file of mediawiki.conf
  copy:
    src: mediawiki.conf
    dest: /etc/apache2/sites-available/
  tags: confapache

- name: Reload configuration apache
  service:
    name: apache2
    state: reloaded
