---

- name: Copy package_2 on LIVR
  copy:
    src: "Package_2/{{item}}"
    dest: "{{mediawiki_LIVR2}}"
  loop:
    - md3_01.01.00_data.tar.gz
    - Theme-REL1_34-b71d3ac.tar.gz
    - LoGo.tar.gz

- name: Unarchive md3_01.01.00_data
  unarchive:
    src: "{{mediawiki_LIVR2}}/md3_01.01.00_data.tar.gz"
    dest: "{{mediawiki_apache}}"
    mode: 0755
    owner: www-data
    group: www-data
    remote_src: yes

- name: Unarchive Theme-REL1_34-b71d3ac
  unarchive:
    src: "{{mediawiki_LIVR2}}/Theme-REL1_34-b71d3ac.tar.gz"
    dest: "{{mediawiki_apache}}/md3_01.01.00_data/extensions/"
    mode: 0755
    owner: www-data
    group: www-data
    remote_src: yes

- name: Unarchive LoGo.tar.gz
  unarchive:
    src: "{{mediawiki_LIVR2}}/LoGo.tar.gz"
    dest: "{{mediawiki_apache}}/md3_01.01.00_data/resources/assets/"
    mode: 0755
    owner: www-data
    group: www-data
    remote_src: yes

- name: Import Localsettings.php
  copy:
    src: LocalSettings.php
    dest: "{{mediawiki_apache}}/md3_01.01.00_data"

- name: Update.php
  command: php "{{mediawiki_apache}}/md3_01.01.00_data/maintenance/update.php"

- name: Reload configuration apache
  service:
    name: apache2
    state: reloaded
