---

- name: Unarchive md3_01.00.00_data
  unarchive:
    src: Package_1/md3_01.00.00_data.tar
    dest: "{{mediawiki_apache}}"
    mode: 0755
    owner: www-data
    group: www-data

- name: Unarchive dump_image.tar.gz
  unarchive:
    src: Package_1/dump_image.tar.gz
    dest: "{{mediawiki_apache}}/md3_01.00.00_data/"
    mode: 0755
    owner: www-data
    group: www-data
    tags: images
