---

- name: Add the ondrej PHP PPA
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Install php
  package:
    name: "{{ item }}"
    state: present
  loop:
    - php
    - php-fpm
    - php-mysql
    - php-xml
    - php-gd
    - php-mbstring

  - apache2_module:
    state : present
      name: proxy_fcgi setenvif
      notify: restart apache2
