---

- name: Add the ondrej PHP PPA
  apt_repository:
    repo: 'ppa:ondrej/php'
    update_cache: yes

- name: Install php
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "php{{php_version}}"
    - "php{{php_version}}-fpm"
    - "php{{php_version}}-mysql"
    - "php{{php_version}}-xml"
    - "php{{php_version}}-gd"
    - "php{{php_version}}-mbstring"

- apache2_module:
    state : present
    name: "{{item}}"
  loop:
    - proxy_fcgi
    - setenvif
  notify: Restart apache2

- meta: flush_handlers

- name: Enabling conf
  command: a2enconf "php{{php_version}}-fpm.conf"
  notify: Restart apache2
