---

- name: Add the ondrej PHP PPA => OK
  apt_repository:
    repo: 'ppa:ondrej/php'
    update_cache: yes

- name: package_facts => récupérer le listing des paquets installés et la version

- name: Tu supprimes les paquets php si php_version est supérieur à la version déjà installée
  apt:
    name: php-*
    state: absent
  when: package_facts.php5 is defined or package_facts.php5 compare php_version

- name: Installer php si php n'est pas déjà installé ou si php_version est supérieur à la version déjà installée


- name: Install php
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "php{{php_versionv1}}"
    - "php{{php_versionv1}}-fpm"
    - "php{{php_versionv1}}-mysql"
    - "php{{php_versionv1}}-xml"
    - "php{{php_versionv1}}-gd"
    - "php{{php_versionv1}}-mbstring"

- apache2_module:
    state : present
    name: "{{item}}"
  loop:
    - proxy_fcgi
    - setenvif
  notify: Restart apache2

- meta: flush_handlers

- name: Enabling conf
  command: a2enconf "php{{php_version}}-fpm.conf"
  notify: Restart apache2

- name: Remove old version
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  loop:
    - "php{{php_versionv1}}"
    - "php{{php_versionv1}}-fpm"
    - "php{{php_versionv1}}-mysql"
    - "php{{php_versionv1}}-xml"
    - "php{{php_versionv1}}-gd"
    - "php{{php_versionv1}}-mbstring"
