---

- name: restart mysql
  service:
    name: mysql
    state: restarted

- name: stop mysql
  service:
    name: mysql
    state: stopped

- name: reload apparmor
  service:
    name: apparmor
    state: reloaded
