---

- name: Fichier de site
  copy:
    src: mediawiki.conf
    dest: /etc/apache2/sites-available/

- name: Disable default conf
  command: a2dissite 000-default

- name: Enable mediawiki.conf
  command: a2ensite mediawiki.conf

- name: Reload configuration apache
  service:
    name: apache2
    state: reloaded

- name: Copy Donnees.xml
  copy:
    src: Package_1/Donnees.xml
    dest: "{{mediawiki_LIVR1}}"

- name: Copy package_1 on LIVR
  copy:
    src: Package_1
    dest: "{{mediawiki_LIVR1}}"

- name: Unarchive md3_01.00.00_data
  unarchive:
    src: "{{mediawiki_LIVR1}}/md3_01.00.00_data.tar"
    dest: "{{mediawiki_apache}}"
    mode: 0755
    owner: www-data
    group: www-data

- name: Install Mediawiki
  command: php "{{mediawiki_apache}}/md3_01.00.00_data/maintenance/install.php" --dbuser=mediawiki_admin --dbpass=mediawiki_passwd --dbname=mediawiki_db --dbserver=localhost --dbtype=mysql --scriptpath= --confpath=/appli/projects/wikidevops/apache/md3_01.00.00_data  --lang=fr --pass=password wikidevops admin

- name: Import Donnees.xml
  command: php "{{mediawiki_apache}}/md3_01.00.00_data/maintenance/importDump.php" "{{mediawiki_LIVR1}}/Donnees.xml"

- name: Rebuild recent changes
  command: php "{{mediawiki_apache}}/md3_01.00.00_data/maintenance/rebuildrecentchanges.php"

- name: Unarchive dump_image.tar.gz
  unarchive:
    src: Package_1/dump_image.tar.gz
    dest: "{{mediawiki_apache}}/md3_01.00.00_data/"
    mode: 0755
    owner: www-data
    group: www-data

- name: Import images
  command: php "{{mediawiki_apache}}/md3_01.00.00_data/maintenance/importImages.php" "{{mediawiki_apache}}/md3_01.00.00_data/images"
