---

- name: File of site
  copy:
    src: mediawiki.conf
    dest: /etc/apache2/sites-available/

- name: Disable default conf
  command: a2dissite 000-default

- name: Enable mediawiki.conf
  command: a2ensite mediawiki.conf

- name: Reload configuration apache
  service:
    name: apache2
    state: reloaded

- name: Copy package_1 on LIVR
  copy:
    src: "Package_1/{{item}}"
    dest: "{{mediawiki_LIVR1}}"
  loop:
    - md3_01.00.00_data.tar
    - Donnees.xml
    - dump_image.tar.gz

- name: Unarchive md3_01.00.00_data
  unarchive:
    src: "{{mediawiki_LIVR1}}/md3_01.00.00_data.tar"
    dest: "{{mediawiki_apache}}"
    mode: 0755
    owner: www-data
    group: www-data
    remote_src: yes

- name: Unarchive images
  unarchive:
    src: "{{mediawiki_LIVR1}}/dump_image.tar.gz"
    dest: "{{mediawiki_apache}}/md3_01.00.00_data/"
    mode: 0755
    owner: www-data
    group: www-data
    remote_src: yes

- name: Install Mediawiki
  command: php "{{mediawiki_apache}}/md3_01.00.00_data/maintenance/install.php" --dbuser=mediawiki_admin --dbpass=mediawiki_passwd --dbname=mediawiki_db --dbserver=localhost --dbtype=mysql --scriptpath= --confpath=/appli/projects/wikidevops/apache/md3_01.00.00_data  --lang=fr --pass=password wikidevops admin
  tags: install

- name: Import Donnees.xml
  command: php "{{mediawiki_apache}}/md3_01.00.00_data/maintenance/importDump.php" "{{mediawiki_LIVR1}}/Donnees.xml"
  tags: install

- name: Rebuild recent changes
  command: php "{{mediawiki_apache}}/md3_01.00.00_data/maintenance/rebuildrecentchanges.php"
  tags: install

- name: Import images
  command: php "{{mediawiki_apache}}/md3_01.00.00_data/maintenance/importImages.php" "{{mediawiki_apache}}/md3_01.00.00_data/images"
